### ISSUE TITLE
Spaces in texts in custom config are removed

### ISSUE THREAD

**Issue by dartcafe** [thomasschwarz96/grav-plugin-simple-cookie#1]
https://github.com/thomasschwarz96/grav-plugin-simple-cookie/blob/3d0ddcbe40d93779da005059e1739e20d5cb0132/templates/partials/init-simple-cookie.html.twig#L18

"content": {
    "message":  "This website uses cookies to ensure you get the best experience on our website." [...]

becomes

Thiswebsiteusescookiestoensureyougetthebestexperienceonourwebsite

**Comment by qw3rtty** [comment]
I committed a bugfix.
Should be available soon on grav.
