### ISSUE TITLE
Clicking got it the dialog comes back on every page

### ISSUE THREAD

**Issue by aiso-net** [thomasschwarz96/grav-plugin-simple-cookie#10]
Ever since version v0.1.7, when Clicking got it the and you go to a new page the dialog comes back again, so the got it button is not working

**Comment by qw3rtty** [comment]
@aiso-net 
Thanks for reporting this Issue! 
I will fix it as soon as I can.

**Comment by randoum** [comment]
Following on this.

By the way, could you include non-minimized versions of your assets? I wanted to fix this and post a PR, but cannot.
Cheers

**Comment by qw3rtty** [comment]
@randoum 
The minimized asset is from [Cookie Consent](https://www.osano.com/cookieconsent).
You can get it from their Website.

**Comment by liebig** [comment]
Unfortunately I have the same problem. Are there any news here yet? There is also no cookie set.

**Comment by randoum** [comment]
Downgrade to 0.1.6

**Comment by qw3rtty** [comment]
I downgraded to 0.1.6.
So I created a new release **0.1.8** for grav.
Should be soon available.
