### ISSUE TITLE
Opt-in possible with free version of  CookieConsent?

### ISSUE THREAD

**Issue by ChristianaHoJo** [thomasschwarz96/grav-plugin-simple-cookie#12]
Is the advanced usage possible without buying a business version of osano CookieConsent JS-libary?

I#am looking forward to your answer!

Greetings,
Christiana

**Comment by qw3rtty** [comment]
Thanks for opening this Issue!
I'm not sure. I will check it out.

**Comment by qw3rtty** [comment]
@ChristianaHoJo 
It is possible to use the advanced options with the Open source JS-Library. 
To use the advanced options you can use the Custom Config section on the Plugin-Page in the Admin area. 
There is a known Issue while using the callbacks. I will fix this in the Future. 

See the [documentation](https://www.osano.com/cookieconsent/documentation/javascript-api/) of Cookie consent for more informations.
