### ISSUE TITLE
Link on Grav Plugin List has 404 error

### ISSUE THREAD

**Issue by firlus** [thomasschwarz96/grav-plugin-simple-cookie#14]
Hey there,
I just noticed that when you click the "Docs" link on getgrav.org/downloads/plugins, you get an 404.
![image](https://user-images.githubusercontent.com/20861553/99229572-7c893a80-27ee-11eb-8721-208dff3f0afa.png)

Best regards,
Michael

**Comment by qw3rtty** [comment]
Thanks for opening this issue!
I will fix it.

**Comment by qw3rtty** [comment]
I fixed it!
It will be soon updated.
