### ISSUE TITLE
"Cookie Policy" Banner always visible on Mobile Devices

### ISSUE THREAD

**Issue by Noxis73** [thomasschwarz96/grav-plugin-simple-cookie#4]
Hi, first of all, thanks for your great work.

I've set up a website with grav and your cookie banner plugin. After Click on "OK", on mobile devices, the "Cookie Policy" Banner doesn't hide like on desktops. (->Screenshot) I haven't found any setup switches. Is there a solution/workaround? Beside that, is it possible to rewrite the label into german?

On desktop, the banner auto-hide fine.

Thanks in advance!

![Screenshot_Cookie-Policy](https://user-images.githubusercontent.com/53949193/75611555-e015ef80-5b1b-11ea-980f-16f6cd258a31.png)

**Comment by qw3rtty** [comment]
Hi @HyknuF 
i will check it out. I will let you know when i got a solution.

**Comment by Noxis73** [comment]
Thanks for your fast response! (Both threads)

Kind regards

**Comment by qw3rtty** [comment]
@HyknuF 
This "mini banner" is a advanced option of cookie consent.
It's for revoke the choosed options for the user.

Here is a link for more informations: https://www.osano.com/cookieconsent/documentation/javascript-api/#revoke_options

So please use the "Custom config" section of the plugin to disable it.
Hope this will work for you.

**Comment by Noxis73** [comment]
Thanks for reply as well. I will check that out. The docu seems to be quite useful.

**Comment by Noxis73** [comment]
Hi, sorry I honestly have to admit, that I didn't figured out how to implement the custom strings? Could you give me some advice?  Thank you very much in advance!

**Comment by qw3rtty** [comment]
@HyknuF 
You don't have to apologize. :) I don't know, what you want to do exactly but i think you want to disable/remove the "mini banner" to revoke the settings.

The correct format for the "Custom config" field is an JavaScript-Object which can be encode/decode to an JSON string.

Here is an working example (it will remove the "mini banner"):
`{"revokable":false, "revokeBtn": "<a></a>"}`
You can just copy and paste this line into the "Custom config" field.

To show both Buttons, you have to choose the Opt-In/Opt-Out option of the "Compliane" select field.

**Comment by Noxis73** [comment]
@thomasschwarz96 thanks for explaination! I think, it worked out :-)
