### ISSUE TITLE
Accept-Button Invisible, only Dismiss-Button visible

### ISSUE THREAD

**Issue by Noxis73** [thomasschwarz96/grav-plugin-simple-cookie#5]
Second Issue i've got; if I label both lines, accept and dismiss, only dismiss shows up on the banner. 

Thanks!

**Comment by qw3rtty** [comment]
@HyknuF 
That's interesting. I will check it out and i will let you know when i got something.

**Comment by qw3rtty** [comment]
@HyknuF 
I got the problem for this one.
I will fix it in the next few days!

**Comment by qw3rtty** [comment]
@HyknuF 
I committed a bugfix.
Now there is a new option in the settings called "Compliance". 
There you have to choose "Opt-In" or "Opt-Out" to show the second button.

For advanced behavior for Opt-In/Opt-Out you can use the "Custom Config" field.
The configurations there will be automatically merged with the default ones.

The bugfix should be available soon on grav.

**Comment by Noxis73** [comment]
Thank you very much for fix that quickly!
