### ISSUE TITLE
Cookie “cookieconsent_status” will be soon rejected 

### ISSUE THREAD

**Issue by rveffer** [thomasschwarz96/grav-plugin-simple-cookie#8]
Firefox browser gives the following warning:

Cookie “cookieconsent_status” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite.

tested on www.veffer.net

**Comment by qw3rtty** [comment]
Hello @rveffer,
thanks, for opening an Issue.

I will check it out.

Regards,
Tom

**Comment by qw3rtty** [comment]
@rveffer 
I did not get the warning in my Firefox.
Which version do you use?

**Comment by rveffer** [comment]
78.0.2 (64-bit)
Firefox for Ubuntu

![CookieWarning_veffer_net](https://user-images.githubusercontent.com/4006030/87859621-bdec0500-c936-11ea-9ab7-1970cc34d2da.png)

**Comment by qw3rtty** [comment]
@rveffer 
Thanks for your quick reply.
I think an update of CookieConsent is required.
I will make it these days.

**Comment by qw3rtty** [comment]
@rveffer 
I updated cookie consent.
An update should be available soon.
