### ISSUE TITLE
Decline button does not show configured text

### ISSUE THREAD

**Issue by rveffer** [thomasschwarz96/grav-plugin-simple-cookie#9]
The Decline button shows "Decline" instead of the text in the config file.

Tested on www.veffer.net

**Comment by qw3rtty** [comment]
Hello @rveffer,
first, thanks for opening an Issue.

Can you paste your config? So i can figure out if there is an bug in the Code or in your config. 

Regards,
Tom

**Comment by rveffer** [comment]
simple-cookie.yaml:

enabled: true
custom: false
position: bottom-right
compliance: opt-out
palette: black
layout: edgeless
informations: 'https://www.veffer.net/gdpr_policy'
banner_message: 'Deze Site gebruikt alleen functionele cookies.'
banner_dismiss: 'Sorry, Nee!'
banner_accept: 'Prima, geen probleem'
banner_policy: 'Lees de policy'
custom_config: null

**Comment by qw3rtty** [comment]
@rveffer  
I could fix the bug.
An update should be available soon.
